name: salesan
services:
  postgres:
    # use this for mac
    platform: linux/amd64
    image: postgres:latest

    # use this for linux
    # platform: linux/x86_64
    # image: postgres:latest

    # ======================= #
    restart: on-failure
    ports:
      - "5432:5432"
    volumes:
      - "./storage/postgres/data:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_PORT: 5432
      POSTGRES_DB: salesan

  redis:
    image: redis:6
    restart: on-failure
    entrypoint:
      - "redis-server"
    volumes:
      - "./storage/redis/conf:/usr/lib/redis/conf"
      - "./storage/redis/modules:/usr/lib/redis/modules"
      - "./storage/redis/data:/data"
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    restart: on-failure
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - ./storage/rabbitmq/data:/var/lib/rabbitmq/
      - ./storage/rabbitmq/log:/var/log/rabbitmq